jobs:
  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install required dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install --disable-pip-version-check --target . werkzeug==1.0.1
      
      - name: Pull Vercel environment information
        run: npx vercel pull --yes --environment=${{ github.event.inputs.environment || 'production' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: npx vercel build --${{ github.event.inputs.environment || 'prod' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to Vercel
        id: vercel-deployment
        run: |
          DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --${{ github.event.inputs.environment || 'prod' }} --token=${{ secrets.VERCEL_TOKEN }})
          echo "VERCEL_DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Print deployment URL
        run: echo "Deployed to ${{ env.VERCEL_DEPLOYMENT_URL }}"

      - name: Test API after deployment
        run: |
          npm install node-fetch
          API_URL="${{ env.VERCEL_DEPLOYMENT_URL }}/api/chat" node scripts/test-api.js

  package-wp-plugin:
    name: Package WordPress Plugin
    runs-on: ubuntu-latest
    needs: deploy-vercel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update plugin with Vercel API URL
        run: |
          API_URL="${{ needs.deploy-vercel.outputs.deployment_url }}/api/chat"
          echo "API_URL=$API_URL"
          echo "{\"api_url\":\"$API_URL\",\"webhook_secret\":\"${{ secrets.WEBHOOK_SECRET }}\"}" > ./wp-plugin/deployment_config.json
      
      - name: Package WordPress plugin
        run: npm run package-plugin
      
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: bookgpt-wp-plugin
          path: dist/bookgpt-wp.zip
          if-no-files-found: error
      
      - name: Create Release
        if: github.event.inputs.environment == 'production' || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/bookgpt-wp.zip
          name: BookGPT WP v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body: |
            BookGPT WordPress Plugin (automatically released)
            
            Changes in this release:
            - Updated with latest Vercel API URL: ${{ needs.deploy-vercel.outputs.deployment_url }}
            - See commit history for detailed changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

